services:
  nginx-proxy:
    build: .
    image: rohammosalli/nginx-proxy:v1
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx-proxy-net
  smartdns-rs:
    image: pikuzheng/smartdns-rs
    container_name: smartdns-rs
    restart: always
    ports:
      - "53:53/udp"
    volumes:
      - ./smartdns/smartdns.conf:/etc/smartdns/smartdns.conf
      - /etc/letsencrypt/live/YOUR_DOMAIN/fullchain.pem:/etc/smartdns/fullchain.pem
      - /etc/letsencrypt/live/YOUR_DOMAIN/privkey.pem:/etc/smartdns/privkey.pem
    networks:
      - nginx-proxy-net  
networks:
  nginx-proxy-net:
